name: knowyourdonor
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  flutter_svg: ^0.20.0-nullsafety.3
  google_maps_flutter: ^2.0.1
  firebase_core: ^0.7.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0
  provider: ^4.3.2+3
  fluttertoast: ^7.1.6
  carousel_slider: ^3.0.0
  geocoding: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
